export const AI_QUOTE_DRAFT_DEFAULT_MODEL = 'gpt-5.4-mini';
export const AI_QUOTE_DRAFT_DESCRIPTION_MAX_LENGTH = 2000;
export const AI_QUOTE_DRAFT_TIMEOUT_MS = 15000;
export const AI_QUOTE_DRAFT_ITEMS_MAX_LENGTH = 50;
export const AI_QUOTE_DRAFT_WARNINGS_MAX_LENGTH = 10;
